# docker-compose -f "deployments/docker-compose.yml" up -d --build
# Specify the version for docker-compose.yml
version: "3.8"

# add the serivces needed (postgres,go-app)
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes: 
      - dbdata:/var/lib/postgresql/data

  goapp:
    container_name: goapp
    # build the Dockerfile, alternatively use an image.
    build:
      context: ..
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"

volumes:
  dbdata: # create the volume for persisting data.