name: CICD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
  
    # Run vet & lint on the code
    - name: Run vet & lint
      run: |
        go vet cmd/goapp/main.go
        golint cmd/goapp/main.go

    - name: Build
      run: go build -o build/goapp cmd/goapp/main.go

    - name: Test
      run: go test -v ./...
